## Import libraries

In [42]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras.layers import InputLayer, Dense
from tensorflow.keras.optimizers import Adam

## Import dataset

In [43]:
dataset = pd.read_csv("life_expectancy.csv", )
dataset.head() #inspect the data

,Country,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
0,Afghanistan,2015,Developing,263.0,62,0.01,71.279624,65.0,1154,19.1,...,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,65.0
1,Afghanistan,2014,Developing,271.0,64,0.01,73.523582,62.0,492,18.6,...,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,59.9
2,Afghanistan,2013,Developing,268.0,66,0.01,73.219243,64.0,430,18.1,...,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,59.9
3,Afghanistan,2012,Developing,272.0,69,0.01,78.184215,67.0,2787,17.6,...,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,59.5
4,Afghanistan,2011,Developing,275.0,71,0.01,7.097109,68.0,3013,17.2,...,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,59.2

In [44]:
#get stas from the data
dataset.describe()

,Year,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
count,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2.938000e+03,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000
mean,2007.518720,164.725664,30.303948,4.546875,738.251295,83.022124,2419.592240,38.381178,42.035739,82.617767,5.924098,82.393125,1.742103,6611.523863,1.023085e+07,4.821886,4.852144,0.630362,12.009837,69.234717
std,4.613841,124.086215,117.926501,3.921946,1987.914858,22.996984,11467.272489,19.935375,160.445548,23.367166,2.400770,23.655562,5.077785,13296.603449,5.402242e+07,4.397621,4.485854,0.205140,3.265139,9.509115
min,2000.000000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.370000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000,36.300000
25%,2004.000000,74.000000,0.000000,1.092500,4.685343,82.000000,0.000000,19.400000,0.000000,78.000000,4.370000,78.000000,0.100000,580.486996,4.189172e+05,1.600000,1.600000,0.504250,10.300000,63.200000
50%,2008.000000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.755000,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000,72.100000
75%,2012.000000,227.000000,22.000000,7.390000,441.534144,96.000000,360.250000,56.100000,28.000000,97.000000,7.330000,97.000000,0.800000,4779.405190,4.584371e+06,7.100000,7.200000,0.772000,14.100000,75.600000
max,2015.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.600000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000,89.000000

Year, we can see the data goes from 2000 to 2015

In [45]:
dataset.drop(["Country"], axis=1, inplace=True)

In [46]:
labels = dataset.iloc[:,-1] #extract labels, life expectancy
features = dataset.iloc[:,0:-1]

In [47]:
features = pd.get_dummies(features)
features.head()

,Year,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,...,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Status_Developed,Status_Developing
0,2015,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,...,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,0,1
1,2014,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,...,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,0,1
2,2013,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,...,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,0,1
3,2012,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,...,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,0,1
4,2011,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,...,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,0,1

In [48]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size=0.20, random_state=23)

In [49]:
numerical_features = features.select_dtypes(include=["float64", "int64"])
numerical_columns = numerical_features.columns
ct = ColumnTransformer([("scaler", StandardScaler(), numerical_columns)], remainder = "passthrough")

In [50]:
features_train_scaled = ct.fit_transform(features_train)
features_test_scaled = ct.transform(features_test)

In [51]:
my_model = Sequential()

In [52]:
num_features = features.shape[1]
input = InputLayer(input_shape = (num_features,))
my_model.add(input)
my_model.add(Dense(64, activation="relu"))
my_model.add(Dense(1))
my_model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                1408

 dense_4 (Dense)             (None, 1)                 65

=================================================================
Total params: 1,473
Trainable params: 1,473
Non-trainable params: 0
_________________________________________________________________

In [53]:
opt = Adam(learning_rate= 0.01)
my_model.compile(loss="mse", metrics = ["mae"], optimizer=opt)

In [54]:
my_model.fit(features_train_scaled, labels_train, epochs = 40, batch_size= 1, verbose=1)

Epoch 1/40
2350/2350 [==============================] - 5s 2ms/step - loss: 148.4267 - mae: 6.4098
Epoch 2/40
2350/2350 [==============================] - 10s 4ms/step - loss: 28.3405 - mae: 3.8582
Epoch 3/40
2350/2350 [==============================] - 12s 5ms/step - loss: 23.9435 - mae: 3.6043
Epoch 4/40
2350/2350 [==============================] - 12s 5ms/step - loss: 26.3183 - mae: 3.5402
Epoch 5/40
2350/2350 [==============================] - 12s 5ms/step - loss: 16.9777 - mae: 3.0650
Epoch 6/40
2350/2350 [==============================] - 10s 4ms/step - loss: 16.7068 - mae: 2.9091
Epoch 7/40
2350/2350 [==============================] - 8s 3ms/step - loss: 16.7942 - mae: 3.0135
Epoch 8/40
2350/2350 [==============================] - 9s 4ms/step - loss: 16.5034 - mae: 2.8676
Epoch 9/40
2350/2350 [==============================] - 8s 3ms/step - loss: 14.0445 - mae: 2.7084
Epoch 10/40
2350/2350 [==============================] - 8s 3ms/step - loss: 14.0528 - mae: 2.6635
Epoch 11/40
2350/2350 [==============================] - 5s 2ms/step - loss: 12.0807 - mae: 2.5868
Epoch 12/40
2350/2350 [==============================] - 8s 4ms/step - loss: 13.6265 - mae: 2.6426
Epoch 13/40
2350/2350 [==============================] - 9s 4ms/step - loss: 13.0552 - mae: 2.5530
Epoch 14/40
2350/2350 [==============================] - 7s 3ms/step - loss: 10.6168 - mae: 2.4321
Epoch 15/40
2350/2350 [==============================] - 6s 3ms/step - loss: 11.3410 - mae: 2.4347
Epoch 16/40
2350/2350 [==============================] - 7s 3ms/step - loss: 13.2575 - mae: 2.5399
Epoch 17/40
2350/2350 [==============================] - 6s 3ms/step - loss: 10.8172 - mae: 2.3414
Epoch 18/40
2350/2350 [==============================] - 6s 3ms/step - loss: 11.0519 - mae: 2.4269
Epoch 19/40
2350/2350 [==============================] - 6s 3ms/step - loss: 9.5021 - mae: 2.3058
Epoch 20/40
2350/2350 [==============================] - 6s 3ms/step - loss: 11.8289 - mae: 2.3885
Epoch 21/40
2350/2350 [==============================] - 6s 2ms/step - loss: 9.7394 - mae: 2.2326
Epoch 22/40
2350/2350 [==============================] - 6s 3ms/step - loss: 8.9899 - mae: 2.2116
Epoch 23/40
2350/2350 [==============================] - 6s 2ms/step - loss: 10.5131 - mae: 2.3198
Epoch 24/40
2350/2350 [==============================] - 6s 3ms/step - loss: 8.5431 - mae: 2.1618
Epoch 25/40
2350/2350 [==============================] - 6s 3ms/step - loss: 8.3140 - mae: 2.1189
Epoch 26/40
2350/2350 [==============================] - 6s 2ms/step - loss: 8.1170 - mae: 2.1155
Epoch 27/40
2350/2350 [==============================] - 7s 3ms/step - loss: 8.9697 - mae: 2.1806
Epoch 28/40
2350/2350 [==============================] - 6s 3ms/step - loss: 8.9217 - mae: 2.1766
Epoch 29/40
2350/2350 [==============================] - 6s 2ms/step - loss: 8.6998 - mae: 2.1477
Epoch 30/40
2350/2350 [==============================] - 6s 3ms/step - loss: 8.2668 - mae: 2.1276
Epoch 31/40
2350/2350 [==============================] - 6s 3ms/step - loss: 7.8374 - mae: 2.0594
Epoch 32/40
2350/2350 [==============================] - 6s 3ms/step - loss: 7.8182 - mae: 2.0592
Epoch 33/40
2350/2350 [==============================] - 6s 2ms/step - loss: 7.5816 - mae: 2.0572
Epoch 34/40
2350/2350 [==============================] - 6s 2ms/step - loss: 7.5035 - mae: 2.0135
Epoch 35/40
2350/2350 [==============================] - 6s 3ms/step - loss: 7.4701 - mae: 2.0228
Epoch 36/40
2350/2350 [==============================] - 6s 3ms/step - loss: 7.8171 - mae: 2.0121
Epoch 37/40
2350/2350 [==============================] - 6s 3ms/step - loss: 6.9484 - mae: 1.9588
Epoch 38/40
2350/2350 [==============================] - 6s 3ms/step - loss: 8.1241 - mae: 2.0486
Epoch 39/40
2350/2350 [==============================] - 6s 2ms/step - loss: 7.0273 - mae: 1.9320
Epoch 40/40
2350/2350 [==============================] - 6s 3ms/step - loss: 7.6541 - mae: 2.0124

In [55]:
res_mse, res_mae = my_model.evaluate(features_test_scaled, labels_test, verbose=0)

In [56]:
print("MAE: ", res_mae)
print("RMSE: ", res_mse)

MAE:  1.906838297843933
RMSE:  7.192779541015625